### ISSUE TITLE
Expanded NPC Dialogue?

### ISSUE THREAD

**Issue by Demorde** [bozimmerman/CoffeeMud#10]
I want to create more dynamic conversations with the NPCs in my MUD, but currently the system is sort of limited. You need to use the dialogue file and reload the mud each time you want to update it.

I'd like to have complex conversations with multiple keywords, which I could dynamically adjust as time goes on. It seems that the quest engine may be the best way to do this, but in general that is a lot more work then it should be.

Is there chance of having a more stream lined / complex / easier to use dialogue engine being introduced?

**Comment by bozimmerman** [comment]
Hi .. it would be easier to comment if some particulars were given, but generally, you never have to reload the mud, except if you make do many Java code changes that you can't remember what all was modified.  However, for mudchat, mobprog scripts, etc, all you have to do is unload the cache after making changes.  use list resources from the command line to see what all there is, find the thing you updated on the list, then use unload resource X to remove it from the cache and force a reload.

This works similarly with scripts, which is what I'd recommend using if you want more dynamic conversations than mudchat.

Hope this helps!
