### ISSUE TITLE
Mudgrinder does not properly generate genStorekeeper.

### ISSUE THREAD

**Issue by PeteKeller** [bozimmerman/CoffeeMud#21]
If you use Mudgrinder to generate a genStorekeeper, it does not have the proper fields.

**Comment by PeteKeller** [comment]
using Mudgrinder, I add a mob to the room, and select stdShopkeeper (not storekeeper).  

When I use Mudgrinder to edit the MOB, I can modify parameters, level, Rejuv. Ticks, and Magic Level.  If I log into my Mud with an ARCHON, and and modify the Storekeeper, I see the same choices.

If I use the ARCHON to generate from inside the mud, I choose a genShopkeeper and that allows me to edit all the Shopkeeper functions.

Also, if I create a genShopkeeper, and look in the room using mudGrinder, the genShopkeeper does not show up in MudGrinder, and is missing from the space if the ARCHON looks for it.

P.S. Sorry about the sketchy initial problem, my daughter rushed me out the door to go shopping.

**Comment by PeteKeller** [comment]
Another thing I noticed this morning.  I can edit the genShopkeeper from Midgaard in Mudgrinder just fine.

**Comment by bozimmerman** [comment]
Well, the difference between stdshopkeeper and genshopkeeper is by design of course.  I can't reproduce any problem with creating a GenShopkeeper in a room, or seeing it or modifying it afterwards.  The bug might have something to do with the specifics of the room, or some field entered after the shopkeeper is created, or something else.   Have you checked your log for errors?

**Comment by PeteKeller** [comment]
No errors in the log.  

From MUDGrinder, I cannot select GenShopkeeper, only StdShopkeeper.

I created a new area, added 4 rooms to it (5 rooms total) and the error still occurred.

I did not modify any fields after creating the  shopkeeper.

Do you want the .cmare of the area?  Do you want my logs?

**Comment by PeteKeller** [comment]
OK, I'm embarrassed, I needed to select new, then genShopkeeper.  I could not find GenShopkeeper from the dropdown.
