### ISSUE TITLE
After "git pull" MUD locks up creating accounts

### ISSUE THREAD

**Issue by fstltna** [bozimmerman/CoffeeMud#27]
I just did a pull from the repo and  when a new user tries and create a account it just hangs for them and spits out a warning on the sever console. Any ideas or do I need to provide more info?

**Comment by bozimmerman** [comment]
I'll definitely take a look at this immediately.  However, I should warn you that pulling from the head of the repos is dangerous, because it represents the last whimsical changes I made, which may or may not be tested.  The official distributions I put out tend to get several weeks of testing with little or no changes, in order to prevent things like this.

**Comment by fstltna** [comment]
I would have wanted it to be the stable version anyway. How do I check out that version?

Marisa

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by bozimmerman** [comment]
The stable releases are kept in several places:  the sourceforge coffeemud repo, the ftp site (ftp://ftp.zimmers.net/pub/projects/coffeemud/5.9) or even from the coffeemud.org home page.  There are other places too, but I don't recall them atm. :)

So, I definitely need more info - I can't reproduce any account creation errors over here.

**Comment by fstltna** [comment]
Ok let me try getting it from the stable repo...

Marisa

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by bozimmerman** [comment]
Cool.  In the meantime, I would still like any info you can provide about this issue.

**Comment by fstltna** [comment]
When I do a clean checkout of the active repo it won't start up at all, I can try and get the errors to you...

Marisa

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by bozimmerman** [comment]
Well, if it's that simple -- no need, I can do that too. :)

**Comment by fstltna** [comment]
Ok let me know...

Marisa 

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by bozimmerman** [comment]
Well, on second thought -- perhaps I do need more.  I did a clean checkout of the git repo, ran make.bat, then mud.bat.  The mud came right up on fakedb, so then I logged in, created a character, smiled, and shut it down.  What am I missing?

**Comment by fstltna** [comment]
Hmm, I'm running on Linux, so I don't use the .bat files just the .sh files. Could that be it?

Marisa

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by bozimmerman** [comment]
No problem -- got that too.
Unfortunately, again, no problems.  Sending me logs might help, along with any any errors you saw in your console.  Also, for Linux, I have to ask if you are using the Sun/Oracle SDK and not OpenSDK.

**Comment by fstltna** [comment]
I will send you those files, and yes I am using the sun jdk...

Marisa

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by phillipjphry** [comment]
Could be a permissions issue, what type of Linux is it? SE?

**Comment by fstltna** [comment]
All my servers are Ubuntu 16.04

And the old version and the stable versions work fine on them

Marisa

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by phillipjphry** [comment]
So not security enhanced. Probably not then. Sorry! I will leave the peanut
gallery.

**Comment by fstltna** [comment]
😉

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for
