### ISSUE TITLE
Clan suggestions 1

### ISSUE THREAD

**Issue by bonnedav** [bozimmerman/CoffeeMud#29]
Here is my first wave of suggestions for clans
1)Allow members to be assigned to multiple positions and add `clanunassign` command.
2)Make the `clanqual` command use its own power and respect voting. Give that power to all positions that can already do it.
3)Change `clanwho` from power CLAN_BENEFITS to power LIST_MEMBERS.
4)Add SET_MORGUE power for `clanmorgue` command instead of SET_HOME.
5)Add a `clanprobation` command to block a clan member from using the clan's channel or journal untell it expires or is removed. Add a power for it and make it only work on those with a lower rank than you. 
6)Allow members with ORDER_CONQUERED to be above the law in conquered areas if that is not already the case.
7)Add LAW power for changing the law in conquered areas instead of ORDER_CONQUERED.
8)Add clan dues that can be set by leaders as a money tax taken from each member into the clan bank. Add commands to set the dues, view your dues, see who owes, and forgive dues. Add powers for setting, viewing the owed list, forgiving, and being exempt. List, forgive, and exempt could probably be the same power. (SET_DUES and FORGIVE_DUES perhaps?)
9)Add clansumon and clanteleport skills usable by enchanters to teleport to and summon clan members.

Feel free to tackle these in any order. Constructive feedback is always appreciated. Thank you.

**Comment by bozimmerman** [comment]
So, I bet most of these things can be done through the government editor.

**Comment by bonnedav** [comment]
Some of them yes but others no. And for any that can i'm asking you to consider a change in defaults.

**Comment by bozimmerman** [comment]
Some of those are good command and power flag ideas though.. thanks!

The anarchy one you can definitely do yourself through the government editor. 

Yea, not changing the defaults on things that are basically artistic decisions.  Sorry.  That's why github has the Fork option. :)

I'll consider the new feature ideas though for sure.

**Comment by bonnedav** [comment]
Fair enough, I understand. That is why the gov editor exists right? The feature ideas are the impotent bit. The editor ones are rilly just asking for a little clairafaction but I will remove them. Thanks.

**Comment by bonnedav** [comment]
Hay, just wondering if any of these have been implemented yet and what the progress is.

**Comment by bozimmerman** [comment]
Final Tally:
1) Skipped - Negative cost/benefit
2) Skipped 
3) Done
4) Skipped
5) Skipped - Do this with clanassign
6) Done
7) Done
8) Done (use clanassign for punishments)
9) Skipped - kneecaps Conjurers

**Comment by bonnedav** [comment]
May a ask why you skipped 2? clanqual seams like something you should be able to be vary specific about who can use it and something that should be voted on. As is now it seams like you can get around vote requirements for invites by setting qualifications. If I am wrong please correct me.

**Comment by bozimmerman** [comment]
Because clanqual and clanpremise currently share the 'premise' security flag, and I see those two things as being tied together.  IOW, who you allow into your clan should be connected to your premise, and vis-versa.
