### ISSUE TITLE
Installing doc error

### ISSUE THREAD

**Issue by drmike** [bozimmerman/CoffeeMud#3]
Re: http://www.coffeemud.net/guides/InstallationGuide.html

The command line for getting the software to run for Unix, Linux, or FreeBSD users is missing a trailing double quote.

java -classpath ".:./lib/js.jar:./lib/jzlib.jar

should actually be:

java -classpath ".:./lib/js.jar:./lib/jzlib.jar"

Drops to a command line without it.

**Comment by bozimmerman** [comment]
Thanks!
