### ISSUE TITLE
5.9.8.1 (fresh install, not upgrade) seems to have issues creating new characters

### ISSUE THREAD

**Issue by z3ndrag0n** [bozimmerman/CoffeeMud#31]
Haven't upgraded for a while so decided to move my working install aside and start fresh. Mud built (though with complaints about the mozilla js packages in the doc building phase) and started up fine, but when I went to telnet in to create my archon, I got the following:
Name: z3ndrag0n

'Z3ndrag0n' is not recognized.
That name is also not available for new players.

(And it didn't seem to matter what name I chose.)

In the end, I hit "*" and it successfully created my initial character, but wondering if there's been a mistake here that most people are missing because upgrades versus fresh installs?

**Comment by bozimmerman** [comment]
Z3ndrag0n is not a legal name, because it contains numbers.  Since you didn't include any other names you chose, I will assume they all contained invalid characters, which would explain the problem.
