### ISSUE TITLE
Incomplete UTF-8 support

### ISSUE THREAD

**Issue by ROBOKiTTY** [bozimmerman/CoffeeMud#33]
Fakedb does not handle UTF-8 correctly. Switching to a different database gets around the issue.

Siplet assumes iso-8859-1 input.

Grinder does not support UTF-8 well. UTF-8 text is not displayed correctly.

**Comment by bozimmerman** [comment]
So, thanks for reporting this, and also, curse you for reporting this.  It is proving insanely tricky to pick telnet codes out of a utf-8 (or 16, etc..) stream, but I'm getting there.

On Grinder, though, can you give an example of where you are seeing text not displayed correctly?

**Comment by ROBOKiTTY** [comment]
On Grinder, editroom.cvmp is one example.

For Siplet, one approach I thought of was to use a list of bytes as the buffer in TelnetFilter and then do something like this:
`
byte b = byteBuffer.get(i);
switch (b & 0xff)
{
case 0: ...
case IAC_:
    ...
    byteBuffer.remove(i);
...
`
Then write the list's backing byte array into an output string in Siplet::getURLData()

**Comment by bozimmerman** [comment]
OK, I think it's all resolved now. Siplet turned out to be the only really difficult fix.. the rest were fairly trivial.  Fixes are in the github head right now.
