### ISSUE TITLE
DOMAIN variable set to empty string when reloading ini file live

### ISSUE THREAD

**Issue by ROBOKiTTY** [bozimmerman/CoffeeMud#35]
There may be others. Restarting server loads the variable correctly.

**Comment by bozimmerman** [comment]
I tried to guess how this was recreated, but guessing is time consuming and usually fruitless.

**Comment by ROBOKiTTY** [comment]
Brand new install, fill in DOMAIN field in coffeemud.ini, build/start server, connect and do reset inifile in game. Webmacro MudInfo?DOMAIN returns an empty string.

**Comment by bozimmerman** [comment]
How do you "reset" the ini file?

**Comment by bozimmerman** [comment]
I've been unable to reproduce.
My steps:
Added @MudInfo?DOMAIN@ to a page.
Viewed the page and confirmed the domain.
logged into the mud as an archon and entered RESET INIFILE on the command line.
Resfreshed the page with the MudInfo macro on it.
Saw the domain was still correct.
