### ISSUE TITLE
Typo - control.cmvp > Player Settings > StartStat

### ISSUE THREAD

**Issue by seamer1977** [bozimmerman/CoffeeMud#37]
Actual:
If this is -1 the system will start all player stats at BASEMINSTAT
and allow the player to spent MAXSTATS - 18 points in any
way they like, though no stat can be spent above BASEMAXSTAT.
Default is 0.

Expected:
If this is -1 the system will start all player stats at BASEMINSTAT
and allow the player to spend MAXSTATS - 18 points in any
way they like, though no stat can be spent above BASEMAXSTAT.
Default is 0.

Change -> spent/spend

**Comment by bozimmerman** [comment]
Fixed!
