### ISSUE TITLE
Siplet > MXP > tags not closing correctly

### ISSUE THREAD

**Issue by seamer1977** [bozimmerman/CoffeeMud#39]
1. Clean install CM onto ubuntu
2. Using Siplet, login as user with MXP enabled (client machine: Safari, macOS Catalina (final build before Big Sur 14.0)
3. Perform any command that gives guaranteed output (score)
4. Click any stat - eg WIS

Result:
</font> tags are sent to Siplet text input box

Note: appears to occur on any MXP-enabled value, not just score>wis. EG Doors, goto, score...

**Comment by bozimmerman** [comment]
![Uploading Image1.jpg…]()
Definitely couldn't repro this.  Maybe it was fixed some time ago?

**Comment by bozimmerman** [comment]
![Uploading Image1.jpg…]()
Definitely couldn't repro this.  Maybe it was fixed some time ago?
