### ISSUE TITLE
Potential (client-dependant) MXP sound string issue?

### ISSUE THREAD

**Issue by Kretol** [bozimmerman/CoffeeMud#4]
Hello!

I have commented out MXP images and sounds.  However, actions that would normally play a sound still show text as if it were partially trying to send a sound command.

For example, when I use a roar social, it shows:
ROOOOOAAAARRRR!!!! <SOUND roar.wav V=50 P=34

Laughing results in:
You laugh. <SOUND laugh.wav V=50 P=19

I say partially because it is indeed cut off like that within the game.  For reference, I use Mudlet 3.0.0-delta.  In MUSHclient, this does not happen.  In the console, Mudlet is detected as "UNKNOWN MXP MSDP GMCP CMP ANSI", whereas MUSHclient is detected as "MXP CMP ANSI."  Any ideas?

**Comment by Kretol** [comment]
Also, forgot to mention, I do have both the SOUND and IMAGE MXP paths commented out in the ini file.

**Comment by bozimmerman** [comment]
You need to put MXP and MSP in your DISABLE= entry in the coffeemud.ini file -- commenting out the paths isn't enough.  Please comment if this fixes your problem.

**Comment by Kretol** [comment]
It did indeed!  Thank you for your assistance!
