### ISSUE TITLE
Enhancement: Please add placeholder text in required fields

### ISSUE THREAD

**Issue by seamer1977** [bozimmerman/CoffeeMud#40]
1. Clean install CM
2. Using an archon, load Holidays in the grinder
3. Click link "Create new" (do not fill the text field)

Result: Nothing appears to occur. It takes a few moments for the realisation you _need_ to fill the text field occurs. Dummy text would be highly useful - eg "Dummy Holiday".

**Comment by bozimmerman** [comment]
Thanks! Fixed
