### ISSUE TITLE
Typo: ArchonGuide.html

### ISSUE THREAD

**Issue by seamer1977** [bozimmerman/CoffeeMud#41]
Text: 
Actual: CREATE
Depending on the argument, this command can bring almost anything into existence, from rooms to doors, from monsters to items. The create command is discussed at length in the sections on building rooms and areas. It is also featured prominantly in theGame Builders Guide.

Expected:
CREATE
Depending on the argument, this command can bring almost anything into existence, from rooms to doors, from monsters to items. The create command is discussed at length in the sections on building rooms and areas. It is also featured prominently in the Game Builders Guide.

Errors:
prominantly > prominently
missing space before `game builders guide` link

**Comment by bozimmerman** [comment]
Fixed
