### ISSUE TITLE
Nice-to-have: word swap in account mananger

### ISSUE THREAD

**Issue by seamer1977** [bozimmerman/CoffeeMud#44]
Please consider changing "E)mail change" to "C)hange email"

Email change -> reminiscent of sending myself a copy of the results of my account changes (adding character, changing pw, changing email - as a result of "write down your new account name and password")
Change email -> change the registered email on my account

<img width="766" alt="Screen Shot 2020-07-06 at 4 10 16 pm" src="https://user-images.githubusercontent.com/4307212/86683616-9308c500-bfb6-11ea-9e57-e29182a9145b.png">

This screenshot also says email is supported - at the time of writing SMTP had been disabled in coffeemud.ini so it's a little unexpected

**Comment by bozimmerman** [comment]
I like E)mail, as it matches the in-game commands, like P)assword, and L)ist, and Q)uit.

Not nice to have -- harmful to have IMHO.
