### ISSUE TITLE
Nice to have: Alert user(s) when updating possessed mobile

### ISSUE THREAD

**Issue by seamer1977** [bozimmerman/CoffeeMud#46]
1) Go to any mobile in-world with Account1
2) Possess mobile using Account1. Do not leave mobile
3) Load MudGrinder with Account2
4) Sign in to MG and load the area > mobile in MG using Account2
5) Modify the mobile in any context you want using Account2
6) Observe Account1 returned back to regular body without any kind of alert
7) Observe Account2 is not warned of Account1's presence

This also occurs if Account1 is modifying the mobile/item via in-game MODIFY command

Background:
Son and I were trying to untangle a thing he didn't know - he via grinder, me via telnet. We kept over-writing each other's modifications and getting very confused on why changes weren't sticking.

Note: 
Ignore child's lack of knowledge, thats nothing to be concerned about... yet...

**Comment by bozimmerman** [comment]
So long as neither the accounts involved, nor the mob are damaged in some way, I'm going to let this slide... it's such an obscure situation, and the "fix" for notifying mudgrinder would be expensive.
