### ISSUE TITLE
Probleme running mud

### ISSUE THREAD

**Issue by blal1** [bozimmerman/CoffeeMud#53]
Hi there, i've trying to install the mud to run it and to build my own server. I've modified the path in mud.bat and make.bat to point to Java app on windows and when i execute the mud.bat, nothing happens

**Comment by AquaTsar17** [comment]
That error means you're trying to run a Java app with a different version of the Runtime than what the app was compiled in. It looks like you have Java 8 on your computer but the MUD was compiled with Java 16. You'll need to get the JRE version 16 and use that to run it, or recompile the project using JDK 8.

**Comment by blal1** [comment]
Hi, i've installed java 16 and it tells that the server has been intialized and when i try to connect to host coffeemud.org and port 5555 nothing happen.
following are messages i've got when i have started the mud.bat file:

20231025.1903.03 info  MUD            CoffeeMud v5.10.2.4
20231025.1903.03 info  MUD            (C) 2000-2023 Bo Zimmerman
20231025.1903.03 info  MUD            http://www.coffeemud.org
20231025.1903.04 info  HOST0          Disabled subsystems: DBERRORQUESTART, COMMAND_POSE, QUITREASON, RETIREREASON
20231025.1903.04 info  MUD@5555       MUD Server started on port: 5555
20231025.1903.04 info  HOST0          Connected to jdbc:fakedb:resources/fakedb
20231025.1903.04 debug HOST0          SSL not configured.
20231025.1903.04 debug HOST0          SSL not configured.
20231025.1903.04 info  SMTP@25        Started on port: 25
20231025.1903.04 info  cweb-admin0    Started http admin0 on port 27777
20231025.1903.04 info  cweb-pub0      Started http pub0 on port 27744
20231025.1903.04 info  cweb-pub0      Started http pub0 on port 80
20231025.1903.04 debug cweb-admin0Tim Timeout Thread started
20231025.1903.04 debug cweb-pub0Timeo Timeout Thread started
20231025.1903.05 info  HOST0          WebMacros loaded  : 200
20231025.1903.06 info  HOST0          MOB Types loaded  : 149
20231025.1903.06 info  HOST0          Exit Types loaded : 31
20231025.1903.06 info  HOST0          Area Types loaded : 14
20231025.1903.06 info  HOST0          Locales loaded    : 127
20231025.1903.07 info  HOST0          Fighter Skills    : 201
20231025.1903.07 info  HOST0          Chants loaded     : 318
20231025.1903.07 info  HOST0          Languages loaded  : 59
20231025.1903.08 info  HOST0          Properties loaded : 312
20231025.1903.09 info  HOST0          Prayers loaded    : 361
20231025.1903.09 info  HOST0          Thief Skills      : 179
20231025.1903.10 info  HOST0          Skills loaded     : 350
20231025.1903.10 info  HOST0          Songs loaded      : 156
20231025.1903.10 info  HOST0          Spells loaded     : 419
20231025.1903.10 info  HOST0          Heroics loaded    : 6
20231025.1903.10 info  HOST0          Tech Skills loaded: 2
20231025.1903.10 info  HOST0          Traps loaded      : 82
20231025.1903.11 info  HOST0          Basic Items loaded: 140
20231025.1903.11 info  HOST0          Weapons loaded    : 62
20231025.1903.11 info  HOST0          Armor loaded      : 51
20231025.1903.12 info  HOST0          Magic Items loaded: 47
20231025.1903.12 info  HOST0          Clan Items loaded : 29
20231025.1903.12 info  HOST0          Electronics loaded: 100
20231025.1903.12 info  HOST0          Behaviors loaded  : 97
20231025.1903.13 info  HOST0          Commands loaded   : 298
20231025.1903.13 info  HOST0          Races loaded      : 249
20231025.1903.13 info  HOST0          Classes loaded    : 54
20231025.1903.17 info  HOST0          Expertises defined: 1820
20231025.1903.17 info  HOST0          Channels loaded   : 21
20231025.1903.17 info  HOST0          Socials loaded    : 338
20231025.1903.17 info  HOST0          Clans loaded      : 0
20231025.1903.17 info  I3Server       InterMud3 Core (c)1996 George Reese
20231025.1903.17 info  CM1Server0@277 Started CM1Server0@27733 on port 27733
20231025.1903.17 error Intermud       Please set ADMINEMAIL in your coffeemud.ini file.
20231025.1903.17 info  Intermud3      I3 client connection: 204.209.44.3@8080
20231025.1903.17 info  I3Server       InterMud3 Server started on port 27766
20231025.1903.18 info  HOST0          Loading catalog...
20231025.1903.18 info  HOST0          Loading map...
20231025.1903.18 info  HOST0          Preparing map...
20231025.1903.18 info  HOST0          Mapped rooms      : 1 in 1 areas
20231025.1903.18 info  HOST0          Quests loaded     : 1
20231025.1903.18 info  HOST0          Services and utilities started
20231025.1903.18 info  HOST0          Host#0 initializated.
20231025.1903.18 info  MUD            Initialization complete.
ps: i have set the domain to coffeemud.org

**Comment by AquaTsar17** [comment]
Whichever computer you're running the MUD on is the server. So, if you're running it on your own machine, you need to use your MUD client to connect to localhost:5555 and that should be enough.

**Comment by blal1** [comment]
Yeah, it works now
Thank you for your help :)
