### ISSUE TITLE
Limit skill use in area/location

### ISSUE THREAD

**Issue by Demorde** [bozimmerman/CoffeeMud#7]
I would like to be able to limit skill use by location, for example mining - it makes no sense, nor would it be appropriate to mine for ore in the sky, or in the middle of a building. I would like to be able to disable skills - the closest thing I have been able to find is ResourceOverride for a behaviour which can only be applied to locations and not areas.

**Comment by bozimmerman** [comment]
A new property, Prop_RestrictSkills, will take care of this gap in the 
next build.

- Bo

**Comment by Demorde** [comment]
Thanks! I look forward to using it in the next release!
